# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'ChapterTest6' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChapterTest6
  pod 'SnapKit'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
end
